### ISSUE TITLE
Make resource models generic

### ISSUE THREAD

**Issue by arueth** [QualiSystems/cloudshell-l1-ixia-xstream#3]
To autoload a chassis you must have a resource model that specifically matches the model value returned from SNMP. We should follow the standard used in other shells and use generics

**Comment by Costya-Y** [comment]
This is not a Shell, it's L1 Driver, as you know they are working a bit differently.
A few weeks ago we have released a new standard for L1 Driver to simplify its usage.
However, there are no plans to update Ixia L1 Driver in the nearest future.
